services:
  djangoapp:
    container_name: nexaflow_backend_pdv
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - postgres

  postgres:
    container_name: nexaflow_postgres_pdv
    image: postgres:18
    volumes:
      - ./data/postgres:/var/lib/postgresql
    env_file:
      - ./dotenv_files/.env