# Generated by Django 6.0.4 on 2026-04-24 22:27

import localflavor.br.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True)),
                ('atualizacao', models.DateField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('OUTRO', 'Outro')], max_length=10)),
                ('cpf', localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('cnpj', localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('name_father', models.CharField(blank=True, max_length=100, null=True)),
                ('name_mother', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('observation', models.TextField(blank=True)),
                ('extra_information', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
