# Generated by Django 6.0.4 on 2026-04-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_options_rename_name_cliente_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='extra_information',
            new_name='informacao_extra',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='name_father',
            new_name='nome_mae',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='name_mother',
            new_name='nome_pai',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='observation',
            new_name='observacao',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telephone',
            new_name='telefone',
        ),
    ]
